### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by not-matthias** [htl-perg-2019-20-5ahif/trippin-exercise-not-matthias#1]
I added the solution for the requirements. @lukas-tr and I made a small version because you said, that it takes maximum 30 lines. :D 

If you want to take a look at the "good" solution, you can see it here: https://github.com/htl-perg-2019-20-5ahif/trippin-exercise-not-matthias/tree/686b922dabe3c16a33184b194eaad567c7d084d3

**Comment by rstropek** [comment]
Nice 👍
